const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.BASE_URL || 'http://127.0.0.1:5093';
(async () => {
  const browser = await chromium.launch({channel:process.env.BROWSER_CHANNEL || 'msedge',headless:true});
  const context = await browser.newContext();
  const page = await context.newPage();
  const errors=[];
  const startupRequests=[];
  page.on("request", request => startupRequests.push(request.url()));
  page.on('pageerror', error => {errors.push(error.message);console.log('PAGE ERROR:',error.message);});
  await page.goto(base + '/timer');
  await page.waitForFunction(() => document.querySelector('#scramble').textContent.includes('Scramble:'));
  await page.waitForFunction(() => window.database && window.account);
  await page.evaluate(() => {enableInspectionSwitch.checked=false;enableLongPressSwitch.checked=false;});
  await page.keyboard.down('Space'); await page.waitForTimeout(100); await page.keyboard.up('Space');
  await page.waitForTimeout(1100);
  await page.keyboard.down('Space'); await page.waitForTimeout(100); await page.keyboard.up('Space');
  await page.waitForFunction(() => document.querySelectorAll('#session tbody tr').length > 0);
  assert(!startupRequests.some(url => url.includes('/images/thumbnails/')), 'Closed settings downloaded background previews');
  assert(!startupRequests.some(url => url.includes('/videos/')), 'Tutorial loaded without being opened');
  assert.equal(await page.evaluate(() => typeof window.videojs), 'undefined');
  console.log('Guest timer, lazy media and IndexedDB save passed');
  if (process.env.READ_ONLY !== '1') {
    const username = 'browser_' + Date.now();
    const password = 'browser-test-password-123';
    await page.goto(base + '/signup');
    await page.locator('#username').fill(username);
    await page.locator('#email').fill(username+'@example.test');
    await page.locator('#password').fill(password);
    await page.locator('#confirmPassword').fill(password);
    await page.locator('button[type=submit]').click();
    await page.locator('#recovery').waitFor({state:'visible'});
    assert((await page.locator('#recovery code').innerText()).length > 20);
    await page.locator('#recovery a').click();
    await page.waitForFunction(() => window.account?.currentUser && document.querySelector('#scramble').textContent.includes('Scramble:'));
    await page.evaluate(() => {enableInspectionSwitch.checked=false;enableLongPressSwitch.checked=false;});
    await page.keyboard.down('Space'); await page.waitForTimeout(100); await page.keyboard.up('Space');
    await page.waitForTimeout(1100);
    await page.keyboard.down('Space'); await page.waitForTimeout(100); await page.keyboard.up('Space');
    await page.waitForFunction(() => document.querySelectorAll('#session tbody tr').length === 1);
    const state = await (await page.request.get(base + '/api/state')).json();
    const uid = await page.evaluate(() => account.currentUser.uid);
    assert.equal(Object.keys(state.times[uid].session1).length, 1);
    const second = await browser.newContext();
    const another = await second.newPage();
    another.on('pageerror', error => errors.push(error.message));
    await another.goto(base + '/signin');
    await another.locator('#username').fill(username);
    await another.locator('#password').fill(password);
    await another.locator('button[type=submit]').click();
    await another.waitForURL(base + '/timer');
    await another.waitForFunction(() => document.querySelectorAll('#session tbody tr').length === 1);
    console.log('Signup, recovery-code display, authenticated timer save and cross-device login/sync passed');
    await second.close();
  }
  await page.screenshot({path:'.artifacts/timer.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(base + '/signup');
  await page.locator('h1').waitFor({state:'visible'});
  const titleBox = await page.locator('h1').boundingBox();
  const headerBox = await page.locator('.mdc-top-app-bar').boundingBox();
  assert(titleBox.y >= headerBox.y + headerBox.height, 'Mobile header overlaps the signup title');
  assert(!(await page.locator('body').innerText()).includes('cubetastic33@gmail.com'));
  await page.screenshot({path:'.artifacts/mobile-signup.png',fullPage:true});
  console.log('Mobile signup layout and independent attribution passed');
  const googleContext = await browser.newContext({viewport:{width:390,height:844}});
  const googlePage = await googleContext.newPage();
  await googlePage.route('**/api/session', route => route.fulfill({json:{csrf:'ui-fixture',user:{uid:'google-ui-fixture',username:'cuber',displayName:'Cuber Example',display_name:'Cuber Example',email:'cuber@example.test',google_linked:true,google_email:'cuber@example.test',has_password:false}}}));
  await googlePage.route('**/api/state', route => route.fulfill({json:{users:{},times:{}}}));
  await googlePage.goto(base + '/profile');
  await googlePage.locator('#googleConnected').waitFor({state:'visible'});
  assert.equal(await googlePage.locator('#accountName').innerText(),'Cuber Example');
  assert.equal(await googlePage.locator('#passwordSection').isVisible(),false);
  assert.equal(await googlePage.locator('#disconnectGoogle').isVisible(),false);
  assert.equal(await googlePage.locator('#googleOnlyHint').isVisible(),true);
  await googlePage.screenshot({path:'.artifacts/google-profile.png',fullPage:true});
  await googleContext.close();
  console.log('Google-only profile and sign-in controls passed');
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('No browser script errors');
})().catch(error => {console.error(error);process.exit(1)});
